### ISSUE TITLE
create and delete event not emitted if folder was freshly created and then deleted within timeout period

### ISSUE THREAD

**Issue by sahiljain2497** [fabiospampinato/watcher#12]
My watcher config is - 

```
{
      ignoreInitial: true,
      recursive: true,
      renameDetection: true,
      renameTimeout: 10000,
      persistent: true,
      ignore(filePath: string) {
        return !!filePath.match(/(^|[\/\\])\../);
      },
    }
```
Is this the correct behaviour? If i create a file and delete it within the timeout period or delete it before create event is emitted, delete is not emitted as well. 

Can we get both the events to emit? Just for consistency and what if we want to track and perform some server-side updates for each of the event.

Is this just happening because renameTimeout is too high?

**Comment by sahiljain2497** [comment]
Also, I tried creating a new folder named jjjjd3 - these two events got emitted - shouldn't this just be one?

directory path got created /Users/sahiljain/Desktop/watch_folder/untitled folder
directory was renamed /Users/sahiljain/Desktop/watch_folder/untitled folder /Users/sahiljain/Desktop/watch_folder/jjjjd3

**Comment by fabiospampinato** [comment]
> Is this the correct behaviour? If i create a file and delete it within the timeout period or delete it before create event is emitted, delete is not emitted as well.

If I'm understanding it correctly no events are emitted in that case?

If so yeah, that's intentional, events are delayed by the value of `renameTimeout`, as that's necessary for detecting renames, you set a very high value so they are delayed by a lot. The default value should work better I think.

> Can we get both the events to emit? 

Getting both sets of events from the same watcher would be very confusing in case where a rename is detected, because what are you supposed to do if the watcher tells you that file X got deleted, then added, then renamed?

If you want both rename events and regular events you can potentially start two watchers, one with rename detection enabled and one with it disabled, they should be cheap enough.

> Also, I tried creating a new folder named jjjjd3 - these two events got emitted - shouldn't this just be one?

If you got those events that's what's happened under the hood. Perhaps the way you created the folder it looked to you like you just created a folder named `jjjjd3`, but in reality a `untitled folder` got created first.

So that seems to work as expected.
