### ISSUE TITLE
Wait writing files to finish

### ISSUE THREAD

**Issue by kodelio** [fabiospampinato/watcher#27]
Hello,
I'm coming from `chokidar` and it has the `awaitWriteFinish` option that is quite useful. It's specified in the `watcher` description that we can use the ignore option to wait writing (e.g you copy a large file, you want to wait it's fully copied to send the event). Could you please provide some example ? 
Thank you

**Comment by fabiospampinato** [comment]
That option is not supported and I don't think it will be supported in the future 🤔

If you don't control how files are written I guess you might have to check on your own if the modification date of a file is old enough or something like that.

If you do control how files are written then what I'd recommend is to write files atomically with [`atomically`](https://github.com/fabiospampinato/atomically), then ignoring temporary files being written by that entirely, with something like this:

```ts
const ignore = targetPath => targetPath.includes ( '.tmp' );
```

The result will be that files being written to won't cause any events, because only temporary files will be written to, which one doesn't generally care for.
