### ISSUE TITLE
Support for awaitWriteFinish

### ISSUE THREAD

**Issue by lindenkron** [fabiospampinato/watcher#29]
From what I can read in the documentation, moving from Chokidar to Watcher doesn't have a equal to Chokidars
`awaitWriteFinish: {
    stabilityThreshold: 2000,
    pollInterval: 100
},`

With Watcher being an alternative to Chokidar, it seems to be a feature that would be desired to have. It's at least one I've been using to great success not having to implement custom logic to not have a an event called before a file is actually ready to be manipulated - and therefore is still locked by Windows.

If I'm missing something or there's any alternatives that I have missed please do tell 🙏 
Outside of that Watcher has seemed good so far for rename event etc.

**Comment by fabiospampinato** [comment]
I'm not interested in this feature for two reasons:

1. If the file is being written to directly, rather than atomically, then the notion of a write "finishing" doesn't really make sense I think. Like you are risking corruption either way potentially. If you want that kind of check you can implement it yourself in your own code I guess.
2. If the file is being written to atomically then writes only happen to the temporary files, never to the "actual" file, and there is no point in watching the temporary one, those should just be ignored, so there's no point in waiting for that to be fully written, even if that made sense.
